package com.bhartiyasaas.stayfile.service.storage;

import java.util.UUID;
import java.util.regex.Pattern;

import com.bhartiyasaas.stayfile.entity.enums.FileCategory;
import com.bhartiyasaas.stayfile.exception.ResourceNotFoundException;

/**
 * Object keys are always generated by the server:
 * <pre>
 *   public/{organizationId}/{categoryFolder}/{uuid}.{ext}
 *   private/{organizationId}/{categoryFolder}/{uuid}.{ext}
 * </pre>
 * Clients never supply a path or filename, and every key coming back from a client is
 * matched against a strict pattern before it touches the file system or Supabase.
 */
public final class StorageKeys {

    private static final String UUID_RE = "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}";
    private static final Pattern VALID_KEY = Pattern.compile(
            "^(public|private)/" + UUID_RE + "/[a-z-]+/" + UUID_RE + "\\.(jpg|png|webp|pdf)$");

    private StorageKeys() {
    }

    public static String newKey(FileCategory category, UUID organizationId, String extension) {
        String visibility = category.isPublicAccess() ? "public" : "private";
        return visibility + "/" + organizationId + "/" + category.getFolder() + "/" + UUID.randomUUID() + "." + extension;
    }

    /** Returns the key unchanged if it is well formed, otherwise behaves as "not found". */
    public static String requireValid(String key) {
        if (key == null || !VALID_KEY.matcher(key).matches()) {
            throw new ResourceNotFoundException("File not found");
        }
        return key;
    }

    public static boolean isPublic(String key) {
        return key.startsWith("public/");
    }

    public static boolean belongsToOrganization(String key, UUID organizationId) {
        return organizationId != null && key.contains("/" + organizationId + "/");
    }

    public static String extensionOf(String key) {
        return key.substring(key.lastIndexOf('.') + 1);
    }

    public static String contentTypeOf(String key) {
        return switch (extensionOf(key)) {
            case "jpg" -> "image/jpeg";
            case "png" -> "image/png";
            case "webp" -> "image/webp";
            case "pdf" -> "application/pdf";
            default -> "application/octet-stream";
        };
    }
}
